### ISSUE TITLE
Add an "auto-generated" comment to generated css file

### ISSUE THREAD

**Issue by davidjagoe** [cdaddr/gaka#2]
The generated css file should start with a comment stating that the file was automatically generated to reduce the chance that a new developer just edits the css file rather than the gaka rules. I've forked the repo and happy to provide a patch.

**Comment by cdaddr** [comment]
I'll leave this up to users to decide whether they want it or not, since it's such an easy function to write on your own.  I'd rather not put it into the library itself.

```
(defn css-with-comment [& rules] (str "CSS auto-generated by Gaka\n" (apply css rules)))
```
